eco/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('', include('maineco.urls', namespace='maineco')),
    
]

maineco/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.contrib.auth.decorators import user_passes_test
from maineco.views import *
from users.views import *
from django.conf.urls.static import static

app_name = 'maineco'

urlpatterns = [
                  path('', main, name='main'),
                  path('about/', about, name='about'),
                  path('login/', user_passes_test(lambda u: u.is_anonymous, '/personal-data')(
                      LoginView.as_view(template_name='login.html')), name="login"),
                  path('logout/', logout, name='logout'),
                  path('signup/', signup, name='signup'),
                  path('signup/update', signup_user, name='signup_user'),
                  path('signup/verification/<hash_code>', validate_hash, name='hash_code'),
                  path('joinevent/', join_event, name='join_event'),

                  path('personal-data/', include('users.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.


class User(AbstractUser):
    username = None
    logo = models.ImageField(upload_to='users_logos', null=True, blank=True, default='users_logos/standart.png')
    phone = models.CharField(unique=True, max_length=200, null=True, blank=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    date_birthday = models.DateField(null=True, blank=True)
    email = models.EmailField(null=False, blank=False, unique=True)
    hash_code = models.CharField(max_length=200, null=True, blank=True)
    is_confirmed = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def is_invited(self, event):
        if self in event.members.all():
            return True
        else:
            return False

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    О нас
{% endblock title %}
{% block content %}
		<main class="uk-section-small" uk-height-viewport="expand: true">
			<div class="uk-container uk-container-large">

				<div class="uk-section-small">
					<div class="uk-child-width-1-1 uk-child-width-1-2@m uk-grid-small" uk-grid>
						<div class="">
							<h1>Стать волонтером - в один клик</h1>
							<p class="uk-text-lead">Сервис для организации, учета и оптимизации создания волонтерских мероприятий. Все это в нашем будущем сервисе!</p>
							<ul class="uk-list iconList">
								<li><i class="fas fa-sign-in-alt fa-2x fa-fw"></i> Регистрируешься и выбираешь интересные тебе мероприятия</li>
								<li><i class="fas fa-recycle fa-2x fa-fw"></i> Делаешь наш мир лучше</li>
								<li><i class="fas fa-star fa-2x fa-fw"></i> Соревнуешься с другими волонтерами, покоряешь рейтинг и получаешь плюшки</li>
							</ul>
						</div>
						<div class="">
							<div class="uk-position-relative">
								<video id="introVideo" class="uk-width-1-1" src="{% static 'img/vid.webm' %}" playsinline autoplay uk-video onloadstart="this.volume=0.5"></video>

								<div class="videoMuteOverlay" uk-toggle="target: .videoMute">
									<i class="fas fa-2x fa-volume-up videoMute" onclick="document.getElementById('introVideo').volume=0"></i>
									<i class="fas fa-2x fa-volume-mute videoMute" onclick="document.getElementById('introVideo').volume=0.5" hidden></i>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="uk-section-small">
					<hr>
					<h2 class="uk-text-center">Наши проекты</h2>
					<div class="uk-child-width-1-1@m uk-child-width-1-2@s uk-child-width-1-4@m uk-grid-small" uk-grid>
						{% for group in groups %}
{#                            <div>#}
{#                                <a href="" {% if forloop.counter > 4 %}class="showMore" hidden{% endif %}>#}
{#                                    <div class="uk-inline-clip uk-transition-toggle borderR" tabindex="0">#}
{#                                        <img data-src="{% static 'img/placeholder.jpg' %}" alt="Название проекта" class="" uk-img>#}
{#                                        <div class="uk-transition-fade uk-position-cover uk-overlay uk-overlay-primary">#}
{#                                            <div class="uk-position-small uk-position-bottom">#}
{#                                                <h3>{{ group.name }}</h3>#}
{#                                                <p>{{ group.small_description }}</p>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </div>#}
                            <div {% if forloop.counter > 4 %}class="showMore" hidden{% endif %}>
							<div class="projectCard">
								<img data-src="{% static 'img/placeholder.jpg' %}" alt="{{ group.name }}"  uk-img>
								<div class="projectCardText">
									<h3>{{ group.name }}</h3>
									<p>{{ group.small_description }}</p>
								</div>
								<a href="" class="projectCardLink"></a>
							</div>
						</div>
                        {% endfor %}

						{% if groups.count > 4 %}<div class="uk-width-1-1 uk-text-center showMore"><button class="uk-button uk-button-secondary" uk-toggle="target: .showMore" type="button">Показать еще</button></div>{% endif %}

					</div>
				</div>

				<div class="uk-section-small">
					<hr>
					<h2 class="uk-text-center">С нами уже работают</h2>
					<div class="uk-position-relative uk-visible-toggle" uk-slider="autoplay: true; autoplay-interval: 1000">
						<div class="uk-slider-container">
							<ul class="uk-slider-items uk-grid-small uk-child-width-1-2 uk-child-width-1-4@s uk-child-width-1-6@m">
								<li><img src="{% static 'img/logos/1.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/2.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/3.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/4.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/5.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/6.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/7.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/8.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/9.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/10.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/11.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/12.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/13.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/14.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/15.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/16.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/17.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/18.png' %}" alt="1"></li>
								<li><img src="{% static 'img/logos/19.png' %}" alt="1"></li>
							</ul>
						</div>
						<a class="uk-position-center-left-out uk-hidden-hover" href="#" uk-slidenav-previous uk-slider-item="previous"></a>
						<a class="uk-position-center-right-out uk-hidden-hover" href="#" uk-slidenav-next uk-slider-item="next"></a>
					</div>
				</div>

				<div class="uk-section-xsmall uk-text-center"><a class="uk-button uk-button-secondary" href="#">Узнать как помочь</a></div>

			</div>
		</main>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock title %}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&display=swap&subset=cyrillic" rel="stylesheet">
		<script src="https://kit.fontawesome.com/d0da235e9e.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<script src="{% static 'js/uikit.min.js' %}"></script>
	</head>
	<body>
		<header>
			<div class="greenBG">
				<div class="uk-container uk-container-large">
					<nav class="uk-navbar-container uk-navbar-transparent uk-navbar" uk-navbar>
						<div class="uk-navbar-left">
							<a class="uk-navbar-item uk-logo" href="{% url 'maineco:main' %}"><img src="img/logo.png" hidden>Чистая Уфа</a>
						</div>
						<div class="uk-navbar-right">
							<ul class="uk-navbar-nav">
								<li><a href="{% url 'maineco:about' %}"><span class="menuHover">О нас</span></a></li>
                            {% if not request.user.is_authenticated %}
								<li>
									<a><span class="menuHover">Личный кабинет</span></a>
									<div class="uk-navbar-dropdown greenBG">
										<ul class="uk-nav uk-navbar-dropdown-nav">
											<li><a href="{% url 'maineco:login' %}">Вход</a></li>
											<li><a href="{% url 'maineco:signup' %}">Регистрация</a></li>
										</ul>
									</div>
								</li>
                            {% endif %}
								{% if request.user.is_authenticated %}
                                <li>
									<a><img class="navAvatar uk-margin-small-right borderR" src="{% if request.user.logo %}{{request.user.logo.url}}{% endif %}"><span class="menuHover">{{request.user.email}}</span></a>
									<div class="uk-navbar-dropdown greenBG">
										<ul class="uk-nav uk-navbar-dropdown-nav">
											<li><a href="{% url 'maineco:maineco:personal_data' %}">Личный кабинет</a></li>
											<li><a href="{% url 'maineco:logout' %}">Выйти</a></li>
										</ul>
									</div>
								</li>
                                {% endif %}
							</ul>
						</div>

					</nav>
				</div>
			</div>
		</header>
        {% block content %}
        {% endblock %}
		<footer class="greenBG">
			<div class="uk-container uk-container-large">
				<div class="uk-grid-small uk-child-width-1-1 uk-child-width-1-2@m" uk-grid>
					<div class="">
						<a class="socIco" href="tel:" target="_blank">+7 909 999 99 99</a>
						<a class="socIco" href="mailto:" target="_blank">mail@domain.com</a>
					</div>
					<div class="">
						<div class="uk-text-right">
							<a class="socIco" href="" target="_blank"><i class="fab fa-fw fa-lg fa-vk"></i></a>
							<a class="socIco" href="" target="_blank"><i class="fab fa-fw fa-lg fa-instagram"></i></a>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="title">
         Очистка водоемов, лесов организация субботников
      </div>
         <div class="menu">
            <a href="#">Грядущие события</a>
            <a href="#">Прошедшие события</a>
            <a href="#">События на сегодня</a>
         </div>
      </div>
      <div class="main">
      {% csrf_token %}
         {% for event in events %}
         <div class="card">
         <div class="card__info">
            <div class="card__date">
                  <div class="time">
                     19:00
                  </div>
                  <div class="day">
                     20.09.2019
                  </div>
               </div>
               <div class="card__text">
                  <h3>
                     {{event.name}}
                  </h3>
                  <p id = 'count_members{{ event.id }}'>
                     {{event.get_count_members}} участника
                  </p>
               </div>
            </div>
            <div class="card__buttons">
               <a id = "{{event.id}}" data-id = "{{event.id}}" class='btn {% if request.user in event.members.all %}dontActive{% endif %}'>{% if request.user in event.members.all %}Вы записаны{% else %}Записаться{% endif %}</a>
               <a href="#">
                  Подробнее
               </a>
            </div>
         </div>
         {% endfor %}
      </div>

      <script>
      $( document ).ready(function() {
         var token = $('input[name="csrfmiddlewaretoken"]').prop('value');
         $('.btn').click(function(){
            $.post(
               "{% url 'maineco:join_event' %}",
               {
                  "id_event": $(this).data('id'),
                  "csrfmiddlewaretoken": token
               }
               ).done(function (data) {
                            var button = data.id_event
                            $("#"+button).text("Вы записаны").addClass("dontActive")
                            $.notify(data.message,data.tag);
                            $('#count_members'+button).text(data.member_count + " участника")
                    })
                .fail(function (xhr) {
                    if (xhr.status === 401){
                        $.notify('Чтобы принять участие в данном мероприятии, необходимо авторизоваться')
                    }
                    else if (xhr.status === 424){
                        $.notify('Чтобы принять участие в данном мероприятии, необходимо подтвердить свой аккаунт')
                    }
                    else{
                        $.notify('При попытке запроса на сервер , произошла ошибка');
                    }

                });
         })
      });
      
      </script>
{% endblock content %}

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Вход</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&display=swap&subset=cyrillic" rel="stylesheet">
		<script src="https://kit.fontawesome.com/d0da235e9e.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<script src="{% static 'js/uikit.min.js' %}"></script>
	</head>
	<body>
		<main>
			<div class="uk-background-cover uk-flex uk-flex-middle uk-flex-center" style="background-image: url({% static 'img/bg.jpg' %});" uk-height-viewport>
				<div class="uk-width-1-1 uk-width-1-2@s uk-width-1-3@m uk-width-1-5@xl uk-padding-small">
					<div class="uk-card uk-card-default uk-card-body">
						<h3 class="uk-card-title">Авторизация</h3>
						<form class="uk-grid-small" uk-grid method="post" action="{% url 'maineco:login' %}">
                        {% csrf_token %}
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-envelope"></i></span>
									<input id="id_username" name="username" class="uk-input" type="email" placeholder="Почта">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-lock"></i></span>
									<a class="uk-form-icon uk-form-icon-flip">
										<span class="showPass" data-type="text" uk-toggle="target: .showPass"><i class="fas fa-eye"></i></span>
										<span class="showPass" data-type="password" uk-toggle="target: .showPass" hidden><i class="fas fa-eye-slash"></i></span>
									</a>
									<input id="id_password" name="password" class="uk-input userPassInput" type="password" placeholder="Пароль">
								</div>
							</div>
							<div class="uk-width-1-1">
                                {% if form.errors %}
                                        <div class="uk-alert-danger" uk-alert>
                                            <a class="uk-alert-close" uk-close></a>
                                            <p>Пожалуйста, введите правильные email и пароль. Оба поля могут быть чувствительны к регистру.</p>
                                        </div>
                                {% endif %}
							</div>
							<div class="uk-width-1-1 uk-text-center">
								<a class="" href="">Восстановить пароль</a>
							</div>
							<div class="uk-width-1-1"><button class="uk-button uk-button-primary uk-width-1-1" type="submit">Войти</button></div>
							<div class="uk-width-1-1"><a class="uk-button uk-button-secondary uk-width-1-1" href="{% url 'maineco:signup' %}">Регистрация</a></div>
						</form>
					</div>
				</div>
			</div>
		</main>
	</body>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</html>

templates/personalData.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

      <div class="container">
          <div class="container-header">
            <p>
                Главная / <b>Личные данные</b>
            </p>
          </div>
          <div class="container-main">
              <div class="pData-list">
                  <div class="pData-list__title">
                      Личные данные
                </div>
                  <div class="pData-list__ul">
                      <ul>
                          <li><a href="#">Личные данные</a></li>
                          <br>
                          <li><a href="#">Мои события</a></li>
                          <br>
                          <li><a href="#">Настройки</a></li>
                      </ul>
                  </div>
              </div>
              <div class="pData">
                  {% if not user.is_confirmed %}
                  <div class="banner">
                        Вам необходимо подтвердить свой аккаунт чтобы пользоватсья сервисом.Письмо с подтверждением на вашей почте.
                  </div>
                  {% endif %}
                <div class="pData-blocks">
                    <div class="pData-block">
                        <div class="pData-block__title">
                            Персональные данные
                        </div>
                        <form action="{% url 'maineco:maineco:personal_update' %}" method="post">
                            {% csrf_token %}
                            <label for="id_last_name">Фамилия</label>
                            <input type="text" name="last_name" maxlength="200" id="id_last_name" value="{{user.last_name|default_if_none:""}}">
                            <label for="id_first_name">Имя</label>
                            <input type="text" name="first_name" maxlength="200" id="id_first_name" value="{{user.first_name|default_if_none:""}}">
                            <label for="id_phone">Номер телефона</label>
                            <input type="text" name="phone" maxlength="200" id="id_phone" value="{{user.phone|default_if_none:""}}">
                            <label for="id_email">E-mail</label>
                            <input type="email" name="email" maxlength="254" required="" id="id_email" value="{{user.email|default_if_none:""}}">
                            <div class="buttons">
                                <button type="submit" id = "save_pers">Сохранить</button>
                            </div>
                        </form>
                    </div>
                    <div class="pData-block">
                            <div class="pData-block__title">
                                Изменение пароля
                            </div>
                            <form action="{% url "maineco:maineco:change_password" %}" method="post">
                                {% csrf_token %}
                                <label for="old_password">Старый пароль</label>
                                <input type="password" name="old_password" autofocus="" required="" id="id_old_password">
                                <label for="new_password1">Новый пароль</label>
                                <input type="password" name="new_password1" autofocus="" required="" id="id_new_password1">
                                <label for="new_password2">Подтвердите новый пароль</label>
                                <input type="password" name="new_password2" autofocus="" required="" id="id_new_password2">
                                <div class="buttons">
                                    <button type="submit">Изменить пароль</button>
                                </div>
                            </form>
                        </div>
                </div>  
              </div>
          </div>
          {% comment %} {% for message in messages %}
          {{message}}
          {% endfor %} {% endcomment %}


{% endblock content %}

templates/reg.html
<!DOCTYPE html>
<html>
	<head>
		<title>Title</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="css/uikit.min.css" />
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&display=swap&subset=cyrillic" rel="stylesheet">
		<script src="https://kit.fontawesome.com/d0da235e9e.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="css/main.css" />
		<script src="js/uikit.min.js"></script>
	</head>
	<body>
		<main>
			<div class="uk-background-cover uk-flex uk-flex-middle uk-flex-center" style="background-image: url(img/bg.jpg);" uk-height-viewport>
				<div class="uk-width-1-1 uk-width-1-3@s uk-width-1-5@xl uk-padding-small">
					<div class="uk-card uk-card-default uk-card-body">
						<h3 class="uk-card-title">Регистрация</h3>

						<form class="uk-grid-small" uk-grid>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-envelope"></i></span>
									<input id="id_email" name="email" class="uk-input" type="email" placeholder="Почта">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-lock"></i></span>
									<a class="uk-form-icon uk-form-icon-flip">
										<span class="showPass" data-type="text" uk-toggle="target: .showPass"><i class="fas fa-eye"></i></span>
										<span class="showPass" data-type="password" uk-toggle="target: .showPass" hidden><i class="fas fa-eye-slash"></i></span>
									</a>
									<input id="userPass" name="userPass" class="uk-input userPassInput" type="password" placeholder="Пароль">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-lock"></i></span>
									<a class="uk-form-icon uk-form-icon-flip">
										<span class="showPass" data-type="text" uk-toggle="target: .showPass"><i class="fas fa-eye"></i></span>
										<span class="showPass" data-type="password" uk-toggle="target: .showPass" hidden><i class="fas fa-eye-slash"></i></span>
									</a>
									<input id="userPassCheck" name="userPassCheck" class="uk-input userPassInput" type="password" placeholder="Повтор пароля">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-alert-danger" uk-alert>
									<a class="uk-alert-close" uk-close></a>
									<p>Ошибочка</p>
								</div>
							</div>
							<div class="uk-width-1-1 uk-text-center">
								<a class="" href="">Восстановить пароль</a>
							</div>
							<div class="uk-width-1-1"><button class="uk-button uk-button-primary uk-width-1-1" type="submit">Регистрация</button></div>
							<div class="uk-width-1-1"><a class="uk-button uk-button-secondary uk-width-1-1" href="#">Войти</a></div>
						</form>
					</div>
				</div>
			</div>
		</main>
	</body>
	<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="js/main.js"></script>
</html>

templates/registration.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Title</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="{% static 'css/uikit.min.css' %}" />
		<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&display=swap&subset=cyrillic" rel="stylesheet">
		<script src="https://kit.fontawesome.com/d0da235e9e.js" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<script src="{% static 'js/uikit.min.js' %}"></script>
	</head>
	<body>
		<main>
			<div class="uk-background-cover uk-flex uk-flex-middle uk-flex-center" style="background-image: url({% static 'img/bg.jpg' %});" uk-height-viewport>
				<div class="uk-width-1-1 uk-width-1-3@s uk-width-1-5@xl uk-padding-small">
					<div class="uk-card uk-card-default uk-card-body">
						<h3 class="uk-card-title">Регистрация</h3>
						<form class="uk-grid-small" uk-grid action="{% url 'maineco:signup_user' %}" method="post">
                            {% csrf_token %}
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-envelope"></i></span>
									<input id="id_email" name="email" class="uk-input" type="email" placeholder="Почта">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-lock"></i></span>
									<a class="uk-form-icon uk-form-icon-flip">
										<span class="showPass" data-type="text" uk-toggle="target: .showPass"><i class="fas fa-eye"></i></span>
										<span class="showPass" data-type="password" uk-toggle="target: .showPass" hidden><i class="fas fa-eye-slash"></i></span>
									</a>
									<input id="id_password1" name="password1" class="uk-input userPassInput" type="password" placeholder="Пароль">
								</div>
							</div>
							<div class="uk-width-1-1">
								<div class="uk-position-relative">
									<span class="uk-form-icon"><i class="fas fa-lock"></i></span>
									<a class="uk-form-icon uk-form-icon-flip">
										<span class="showPass" data-type="text" uk-toggle="target: .showPass"><i class="fas fa-eye"></i></span>
										<span class="showPass" data-type="password" uk-toggle="target: .showPass" hidden><i class="fas fa-eye-slash"></i></span>
									</a>
									<input id="id_password2" name="password2" class="uk-input userPassInput" type="password" placeholder="Повтор пароля">
								</div>
							</div>
							<div class="uk-width-1-1">
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="uk-alert-danger" uk-alert>
                                            <a class="uk-alert-close" uk-close></a>
                                            <p>{{message}}</p>
                                        </div>
                                    {% endfor %}
							    {% endif %}
                            </div>
							<div class="uk-width-1-1 uk-text-center">
								<a class="" href="">Восстановить пароль</a>
							</div>
							<div class="uk-width-1-1"><button class="uk-button uk-button-primary uk-width-1-1" type="submit">Регистрация</button></div>
							<div class="uk-width-1-1"><a class="uk-button uk-button-secondary uk-width-1-1" href="{% url 'maineco:login' %}">Войти</a></div>
						</form>
					</div>
				</div>
			</div>
		</main>
	</body>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
	<script src="{% static 'js/main.js' %}"></script>
</html>